'use strict';

const config = require('./config');
const github = require('./github');
const llm = require('./llm');
const { SYSTEM_PROMPT, buildUserMessage, parseReviewResponse } = require('./prompt');

function isSkippedFile(path) {
  const name = path.split('/').pop();
  return config.skipPatterns.some((pattern) => {
    if (pattern.startsWith('*.')) {
      return name.endsWith(pattern.slice(1));
    }
    if (pattern.startsWith('*.') === false && pattern.includes('*')) {
      // Simple glob: convert to regex.
      const re = new RegExp('^' + pattern.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*') + '$');
      return re.test(name) || re.test(path);
    }
    return name === pattern || path === pattern;
  });
}

/**
 * Build the diff text from the PR files API response.
 * Excludes deleted files, dependency lock files, and binary files.
 */
function buildDiff(files) {
  const parts = [];
  let total = 0;
  let excludedDeleted = 0;
  let excludedSkipped = 0;
  for (const f of files) {
    if (f.status === 'removed') {
      excludedDeleted += 1;
      continue;
    }
    if (isSkippedFile(f.filename)) {
      excludedSkipped += 1;
      continue;
    }
    if (!f.patch) continue; // binary files have no patch
    const header = `diff --git a/${f.filename} b/${f.filename}\n--- a/${f.filename}\n+++ b/${f.filename}\n`;
    const chunk = header + f.patch + '\n';
    if (total + chunk.length > config.maxDiffChars) {
      parts.push('... [diff truncated: remaining files omitted] ...');
      break;
    }
    parts.push(chunk);
    total += chunk.length;
  }

  const notes = [];
  if (excludedDeleted > 0) notes.push(`${excludedDeleted} deleted file(s) excluded`);
  if (excludedSkipped > 0) notes.push(`${excludedSkipped} dependency/generated file(s) excluded`);
  if (notes.length > 0) {
    parts.push(`[note: ${notes.join('; ')} — review only the files shown above]`);
  }
  return parts.join('\n');
}

/**
 * Pick a few small changed files to include as full-file context.
 */
async function gatherContextFiles(owner, repo, files, headRef) {
  const candidates = files
    .filter((f) => !isSkippedFile(f.filename) && f.status !== 'removed' && f.status !== 'renamed')
    .filter((f) => f.additions + f.deletions > 0)
    .sort((a, b) => (a.additions + a.deletions) - (b.additions + b.deletions))
    .slice(0, config.maxContextFiles);

  const out = [];
  for (const f of candidates) {
    try {
      const content = await github.getFileContent(owner, repo, f.filename, headRef);
      if (content && content.length <= config.maxContextFileChars) {
        out.push({ path: f.filename, content });
      }
    } catch {
      // File may be too large or missing; skip it.
    }
  }
  return out;
}

/**
 * Run the full review pipeline for one PR.
 */
async function reviewPullRequest(owner, repo, number) {
  const pr = await github.getPullRequest(owner, repo, number);
  if (pr.state !== 'open') {
    throw new Error(`PR #${number} is not open (state: ${pr.state})`);
  }

  const files = await github.getPullRequestFiles(owner, repo, number);
  const diff = buildDiff(files);
  if (!diff.trim()) {
    throw new Error('No reviewable diff (all files skipped or binary)');
  }

  const contextFiles = await gatherContextFiles(owner, repo, files, pr.head.ref);

  const userMessage = buildUserMessage({
    title: pr.title,
    description: pr.body,
    diff,
    contextFiles,
  });

  const raw = await llm.chatCompletion({ system: SYSTEM_PROMPT, user: userMessage });
  const review = parseReviewResponse(raw);

  // Cap comment count.
  const comments = review.comments.slice(0, config.maxComments);

  // Decide the review event.
  let event = 'COMMENT';
  if (review.critical) {
    if (config.reviewMode === 'auto' || config.reviewMode === 'request_changes_if_critical') {
      event = 'REQUEST_CHANGES';
    }
  } else if (config.reviewMode === 'auto') {
    event = 'APPROVE';
  }

  const body = [
    `## 🤖 AI Code Review`,
    ``,
    review.summary,
    ``,
    `---`,
    `_Generated by github-ai-review (LLM: ${config.litellmModel}). This is an automated review and may contain mistakes — treat it as a suggestion, not a verdict._`,
  ].join('\n');

  const result = await github.createReview({
    owner,
    repo,
    number,
    body,
    event,
    comments,
  });

  return { review, event, reviewId: result.id };
}

module.exports = { reviewPullRequest, isSkippedFile, buildDiff };
